/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/campus-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/company-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Companysignup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Studentsignup`; params?: Router.UnknownInputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/campus-signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/college`; params?: Router.UnknownInputParams; } | { pathname: `/campusLogin`; params?: Router.UnknownInputParams; } | { pathname: `/companyLogin`; params?: Router.UnknownInputParams; } | { pathname: `/StudentLogin`; params?: Router.UnknownInputParams; } | { pathname: `/CompanyLogin`; params?: Router.UnknownInputParams; } | { pathname: `/CampusLogin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/campus-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/company-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/Companysignup`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Studentsignup`; params?: Router.UnknownOutputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/campus-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/college`; params?: Router.UnknownOutputParams; } | { pathname: `/campusLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/companyLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/StudentLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/CompanyLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/CampusLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/campus-dashboard${`?${string}` | `#${string}` | ''}` | `/company-dashboard${`?${string}` | `#${string}` | ''}` | `/Companysignup${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Studentsignup${`?${string}` | `#${string}` | ''}` | `/student-dashboard${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/campus-signup${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/college${`?${string}` | `#${string}` | ''}` | `/campusLogin${`?${string}` | `#${string}` | ''}` | `/companyLogin${`?${string}` | `#${string}` | ''}` | `/StudentLogin${`?${string}` | `#${string}` | ''}` | `/CompanyLogin${`?${string}` | `#${string}` | ''}` | `/CampusLogin${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/campus-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/company-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Companysignup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Studentsignup`; params?: Router.UnknownInputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/campus-signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/college`; params?: Router.UnknownInputParams; } | { pathname: `/campusLogin`; params?: Router.UnknownInputParams; } | { pathname: `/companyLogin`; params?: Router.UnknownInputParams; } | { pathname: `/StudentLogin`; params?: Router.UnknownInputParams; } | { pathname: `/CompanyLogin`; params?: Router.UnknownInputParams; } | { pathname: `/CampusLogin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
